<?php
/**
 * Table:Acl mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Acl extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='Acl';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'user_id' => 
  array (
    'name' => 'user_id',
    'type' => 'N',
    'length' => '11',
  ),
  'role_id' => 
  array (
    'name' => 'role_id',
    'type' => 'N',
    'length' => '11',
  ),
  'resource' => 
  array (
    'name' => 'resource',
    'type' => 'S',
    'length' => '25',
  ),
  'privilege' => 
  array (
    'name' => 'privilege',
    'type' => 'S',
    'length' => '50',
  ),
  'police' => 
  array (
    'name' => 'police',
    'type' => 'S',
    'length' => '1',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Acl
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'user_id'的值
     *
     * @param  integer $value
     * 
     * @return Acl
     */
    public function setUserId($value){
        $this->set('user_id',$value);
        return $this;
    }
    /**
     * 获取属性:'user_id'的值
     * 
     * @return integer
     */
    public function getUserId(){
        return $this->get('user_id');
    }
        /**
     * 设置属性'role_id'的值
     *
     * @param  integer $value
     * 
     * @return Acl
     */
    public function setRoleId($value){
        $this->set('role_id',$value);
        return $this;
    }
    /**
     * 获取属性:'role_id'的值
     * 
     * @return integer
     */
    public function getRoleId(){
        return $this->get('role_id');
    }
        /**
     * 设置属性'resource'的值
     *
     * @param  string $value
     * 
     * @return Acl
     */
    public function setResource($value){
        $this->set('resource',$value);
        return $this;
    }
    /**
     * 获取属性:'resource'的值
     * 
     * @return string
     */
    public function getResource(){
        return $this->get('resource');
    }
        /**
     * 设置属性'privilege'的值
     *
     * @param  string $value
     * 
     * @return Acl
     */
    public function setPrivilege($value){
        $this->set('privilege',$value);
        return $this;
    }
    /**
     * 获取属性:'privilege'的值
     * 
     * @return string
     */
    public function getPrivilege(){
        return $this->get('privilege');
    }
        /**
     * 设置属性'police'的值
     *
     * @param  string $value
     * 
     * @return Acl
     */
    public function setPolice($value){
        $this->set('police',$value);
        return $this;
    }
    /**
     * 获取属性:'police'的值
     * 
     * @return string
     */
    public function getPolice(){
        return $this->get('police');
    }
    }
/**vim:sw=4 et ts=4 **/
?>