<?php
/**
 * Table:advertise mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Advertise extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='advertise';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '4',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '100',
  ),
  'number' => 
  array (
    'name' => 'number',
    'type' => 'S',
    'length' => '30',
  ),
  'alias' => 
  array (
    'name' => 'alias',
    'type' => 'S',
    'length' => '100',
  ),
  'link' => 
  array (
    'name' => 'link',
    'type' => 'S',
    'length' => '220',
  ),
  'body' => 
  array (
    'name' => 'body',
    'type' => 'S',
    'length' => -1,
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
  'updated_on' => 
  array (
    'name' => 'updated_on',
    'type' => 'T',
    'length' => -1,
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Advertise
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'number'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setNumber($value){
        $this->set('number',$value);
        return $this;
    }
    /**
     * 获取属性:'number'的值
     * 
     * @return string
     */
    public function getNumber(){
        return $this->get('number');
    }
        /**
     * 设置属性'alias'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setAlias($value){
        $this->set('alias',$value);
        return $this;
    }
    /**
     * 获取属性:'alias'的值
     * 
     * @return string
     */
    public function getAlias(){
        return $this->get('alias');
    }
        /**
     * 设置属性'link'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setLink($value){
        $this->set('link',$value);
        return $this;
    }
    /**
     * 获取属性:'link'的值
     * 
     * @return string
     */
    public function getLink(){
        return $this->get('link');
    }
        /**
     * 设置属性'body'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setBody($value){
        $this->set('body',$value);
        return $this;
    }
    /**
     * 获取属性:'body'的值
     * 
     * @return string
     */
    public function getBody(){
        return $this->get('body');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return Advertise
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'updated_on'的值
     *
     * @param  date $value
     * 
     * @return Advertise
     */
    public function setUpdatedOn($value){
        $this->set('updated_on',$value);
        return $this;
    }
    /**
     * 获取属性:'updated_on'的值
     * 
     * @return date
     */
    public function getUpdatedOn(){
        return $this->get('updated_on');
    }
    }
/**vim:sw=4 et ts=4 **/
?>