<?php
/**
 * Table:comment mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Comment extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='comment';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'S',
    'length' => '11',
  ),
  'target_id' => 
  array (
    'name' => 'target_id',
    'type' => 'S',
    'length' => '11',
  ),
  'user_id' => 
  array (
    'name' => 'user_id',
    'type' => 'S',
    'length' => '11',
  ),
  'username' => 
  array (
    'name' => 'username',
    'type' => 'S',
    'length' => '100',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '100',
  ),
  'content' => 
  array (
    'name' => 'content',
    'type' => 'S',
    'length' => -1,
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
  'ip' => 
  array (
    'name' => 'ip',
    'type' => 'S',
    'length' => '15',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return string
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'target_id'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setTargetId($value){
        $this->set('target_id',$value);
        return $this;
    }
    /**
     * 获取属性:'target_id'的值
     * 
     * @return string
     */
    public function getTargetId(){
        return $this->get('target_id');
    }
        /**
     * 设置属性'user_id'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setUserId($value){
        $this->set('user_id',$value);
        return $this;
    }
    /**
     * 获取属性:'user_id'的值
     * 
     * @return string
     */
    public function getUserId(){
        return $this->get('user_id');
    }
        /**
     * 设置属性'username'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setUsername($value){
        $this->set('username',$value);
        return $this;
    }
    /**
     * 获取属性:'username'的值
     * 
     * @return string
     */
    public function getUsername(){
        return $this->get('username');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'content'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setContent($value){
        $this->set('content',$value);
        return $this;
    }
    /**
     * 获取属性:'content'的值
     * 
     * @return string
     */
    public function getContent(){
        return $this->get('content');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'ip'的值
     *
     * @param  string $value
     * 
     * @return Comment
     */
    public function setIp($value){
        $this->set('ip',$value);
        return $this;
    }
    /**
     * 获取属性:'ip'的值
     * 
     * @return string
     */
    public function getIp(){
        return $this->get('ip');
    }
    }
/**vim:sw=4 et ts=4 **/
?>