<?php
/**
 * Table:Content mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Content extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='Content';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '75',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '30',
  ),
  'excerpt' => 
  array (
    'name' => 'excerpt',
    'type' => 'S',
    'length' => '245',
  ),
  'body' => 
  array (
    'name' => 'body',
    'type' => 'S',
    'length' => -1,
  ),
  'author' => 
  array (
    'name' => 'author',
    'type' => 'S',
    'length' => '25',
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'tags' => 
  array (
    'name' => 'tags',
    'type' => 'S',
    'length' => '100',
  ),
  'asset_id' => 
  array (
    'name' => 'asset_id',
    'type' => 'N',
    'length' => '11',
  ),
  'store_id' => 
  array (
    'name' => 'store_id',
    'type' => 'N',
    'length' => '4',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'T',
    'length' => -1,
  ),
  'created_by' => 
  array (
    'name' => 'created_by',
    'type' => 'N',
    'length' => '11',
  ),
  'published_on' => 
  array (
    'name' => 'published_on',
    'type' => 'T',
    'length' => -1,
  ),
  'published_by' => 
  array (
    'name' => 'published_by',
    'type' => 'N',
    'length' => '11',
  ),
  'status' => 
  array (
    'name' => 'status',
    'type' => 'S',
    'length' => '4',
  ),
  'stick' => 
  array (
    'name' => 'stick',
    'type' => 'S',
    'length' => '1',
  ),
  'version' => 
  array (
    'name' => 'version',
    'type' => 'S',
    'length' => '1',
  ),
  'is_comment' => 
  array (
    'name' => 'is_comment',
    'type' => 'S',
    'length' => '1',
  ),
  'post_type' => 
  array (
    'name' => 'post_type',
    'type' => 'S',
    'length' => '20',
  ),
  'comment_count' => 
  array (
    'name' => 'comment_count',
    'type' => 'N',
    'length' => '4',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'excerpt'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setExcerpt($value){
        $this->set('excerpt',$value);
        return $this;
    }
    /**
     * 获取属性:'excerpt'的值
     * 
     * @return string
     */
    public function getExcerpt(){
        return $this->get('excerpt');
    }
        /**
     * 设置属性'body'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setBody($value){
        $this->set('body',$value);
        return $this;
    }
    /**
     * 获取属性:'body'的值
     * 
     * @return string
     */
    public function getBody(){
        return $this->get('body');
    }
        /**
     * 设置属性'author'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setAuthor($value){
        $this->set('author',$value);
        return $this;
    }
    /**
     * 获取属性:'author'的值
     * 
     * @return string
     */
    public function getAuthor(){
        return $this->get('author');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'tags'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setTags($value){
        $this->set('tags',$value);
        return $this;
    }
    /**
     * 获取属性:'tags'的值
     * 
     * @return string
     */
    public function getTags(){
        return $this->get('tags');
    }
        /**
     * 设置属性'asset_id'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setAssetId($value){
        $this->set('asset_id',$value);
        return $this;
    }
    /**
     * 获取属性:'asset_id'的值
     * 
     * @return integer
     */
    public function getAssetId(){
        return $this->get('asset_id');
    }
        /**
     * 设置属性'store_id'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setStoreId($value){
        $this->set('store_id',$value);
        return $this;
    }
    /**
     * 获取属性:'store_id'的值
     * 
     * @return integer
     */
    public function getStoreId(){
        return $this->get('store_id');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  date $value
     * 
     * @return Content
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return date
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'created_by'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setCreatedBy($value){
        $this->set('created_by',$value);
        return $this;
    }
    /**
     * 获取属性:'created_by'的值
     * 
     * @return integer
     */
    public function getCreatedBy(){
        return $this->get('created_by');
    }
        /**
     * 设置属性'published_on'的值
     *
     * @param  date $value
     * 
     * @return Content
     */
    public function setPublishedOn($value){
        $this->set('published_on',$value);
        return $this;
    }
    /**
     * 获取属性:'published_on'的值
     * 
     * @return date
     */
    public function getPublishedOn(){
        return $this->get('published_on');
    }
        /**
     * 设置属性'published_by'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setPublishedBy($value){
        $this->set('published_by',$value);
        return $this;
    }
    /**
     * 获取属性:'published_by'的值
     * 
     * @return integer
     */
    public function getPublishedBy(){
        return $this->get('published_by');
    }
        /**
     * 设置属性'status'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setStatus($value){
        $this->set('status',$value);
        return $this;
    }
    /**
     * 获取属性:'status'的值
     * 
     * @return string
     */
    public function getStatus(){
        return $this->get('status');
    }
        /**
     * 设置属性'stick'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setStick($value){
        $this->set('stick',$value);
        return $this;
    }
    /**
     * 获取属性:'stick'的值
     * 
     * @return string
     */
    public function getStick(){
        return $this->get('stick');
    }
        /**
     * 设置属性'version'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setVersion($value){
        $this->set('version',$value);
        return $this;
    }
    /**
     * 获取属性:'version'的值
     * 
     * @return string
     */
    public function getVersion(){
        return $this->get('version');
    }
        /**
     * 设置属性'is_comment'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setIsComment($value){
        $this->set('is_comment',$value);
        return $this;
    }
    /**
     * 获取属性:'is_comment'的值
     * 
     * @return string
     */
    public function getIsComment(){
        return $this->get('is_comment');
    }
        /**
     * 设置属性'post_type'的值
     *
     * @param  string $value
     * 
     * @return Content
     */
    public function setPostType($value){
        $this->set('post_type',$value);
        return $this;
    }
    /**
     * 获取属性:'post_type'的值
     * 
     * @return string
     */
    public function getPostType(){
        return $this->get('post_type');
    }
        /**
     * 设置属性'comment_count'的值
     *
     * @param  integer $value
     * 
     * @return Content
     */
    public function setCommentCount($value){
        $this->set('comment_count',$value);
        return $this;
    }
    /**
     * 获取属性:'comment_count'的值
     * 
     * @return integer
     */
    public function getCommentCount(){
        return $this->get('comment_count');
    }
    }
/**vim:sw=4 et ts=4 **/
?>