<?php
/**
 * Table:content_block mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_ContentBlock extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='content_block';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '40',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '40',
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '4',
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'version' => 
  array (
    'name' => 'version',
    'type' => 'S',
    'length' => '1',
  ),
  'template_id' => 
  array (
    'name' => 'template_id',
    'type' => 'N',
    'length' => '11',
  ),
  'thumb_type' => 
  array (
    'name' => 'thumb_type',
    'type' => 'S',
    'length' => '2',
  ),
  'auto' => 
  array (
    'name' => 'auto',
    'type' => 'N',
    'length' => '4',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return ContentBlock
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'version'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setVersion($value){
        $this->set('version',$value);
        return $this;
    }
    /**
     * 获取属性:'version'的值
     * 
     * @return string
     */
    public function getVersion(){
        return $this->get('version');
    }
        /**
     * 设置属性'template_id'的值
     *
     * @param  integer $value
     * 
     * @return ContentBlock
     */
    public function setTemplateId($value){
        $this->set('template_id',$value);
        return $this;
    }
    /**
     * 获取属性:'template_id'的值
     * 
     * @return integer
     */
    public function getTemplateId(){
        return $this->get('template_id');
    }
        /**
     * 设置属性'thumb_type'的值
     *
     * @param  string $value
     * 
     * @return ContentBlock
     */
    public function setThumbType($value){
        $this->set('thumb_type',$value);
        return $this;
    }
    /**
     * 获取属性:'thumb_type'的值
     * 
     * @return string
     */
    public function getThumbType(){
        return $this->get('thumb_type');
    }
        /**
     * 设置属性'auto'的值
     *
     * @param  integer $value
     * 
     * @return ContentBlock
     */
    public function setAuto($value){
        $this->set('auto',$value);
        return $this;
    }
    /**
     * 获取属性:'auto'的值
     * 
     * @return integer
     */
    public function getAuto(){
        return $this->get('auto');
    }
    }
/**vim:sw=4 et ts=4 **/
?>