<?php
/**
 * Table:grade mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Grade extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='grade';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'user_id' => 
  array (
    'name' => 'user_id',
    'type' => 'N',
    'length' => '11',
  ),
  'target_id' => 
  array (
    'name' => 'target_id',
    'type' => 'N',
    'length' => '11',
  ),
  'rate' => 
  array (
    'name' => 'rate',
    'type' => 'N',
    'length' => '4',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Grade
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'user_id'的值
     *
     * @param  integer $value
     * 
     * @return Grade
     */
    public function setUserId($value){
        $this->set('user_id',$value);
        return $this;
    }
    /**
     * 获取属性:'user_id'的值
     * 
     * @return integer
     */
    public function getUserId(){
        return $this->get('user_id');
    }
        /**
     * 设置属性'target_id'的值
     *
     * @param  integer $value
     * 
     * @return Grade
     */
    public function setTargetId($value){
        $this->set('target_id',$value);
        return $this;
    }
    /**
     * 获取属性:'target_id'的值
     * 
     * @return integer
     */
    public function getTargetId(){
        return $this->get('target_id');
    }
        /**
     * 设置属性'rate'的值
     *
     * @param  integer $value
     * 
     * @return Grade
     */
    public function setRate($value){
        $this->set('rate',$value);
        return $this;
    }
    /**
     * 获取属性:'rate'的值
     * 
     * @return integer
     */
    public function getRate(){
        return $this->get('rate');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return Grade
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
    }
/**vim:sw=4 et ts=4 **/
?>