<?php
/**
 * Table:meta mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Meta extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='meta';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'S',
    'length' => '11',
  ),
  'owner_id' => 
  array (
    'name' => 'owner_id',
    'type' => 'N',
    'length' => '11',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '100',
  ),
  'value' => 
  array (
    'name' => 'value',
    'type' => 'S',
    'length' => -1,
  ),
  'tmp_id' => 
  array (
    'name' => 'tmp_id',
    'type' => 'S',
    'length' => '11',
  ),
  'domain' => 
  array (
    'name' => 'domain',
    'type' => 'S',
    'length' => '100',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  string $value
     * 
     * @return Meta
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return string
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'owner_id'的值
     *
     * @param  integer $value
     * 
     * @return Meta
     */
    public function setOwnerId($value){
        $this->set('owner_id',$value);
        return $this;
    }
    /**
     * 获取属性:'owner_id'的值
     * 
     * @return integer
     */
    public function getOwnerId(){
        return $this->get('owner_id');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return Meta
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'value'的值
     *
     * @param  string $value
     * 
     * @return Meta
     */
    public function setValue($value){
        $this->set('value',$value);
        return $this;
    }
    /**
     * 获取属性:'value'的值
     * 
     * @return string
     */
    public function getValue(){
        return $this->get('value');
    }
        /**
     * 设置属性'tmp_id'的值
     *
     * @param  string $value
     * 
     * @return Meta
     */
    public function setTmpId($value){
        $this->set('tmp_id',$value);
        return $this;
    }
    /**
     * 获取属性:'tmp_id'的值
     * 
     * @return string
     */
    public function getTmpId(){
        return $this->get('tmp_id');
    }
        /**
     * 设置属性'domain'的值
     *
     * @param  string $value
     * 
     * @return Meta
     */
    public function setDomain($value){
        $this->set('domain',$value);
        return $this;
    }
    /**
     * 获取属性:'domain'的值
     * 
     * @return string
     */
    public function getDomain(){
        return $this->get('domain');
    }
    }
/**vim:sw=4 et ts=4 **/
?>