<?php
/**
 * Table:orders mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Orders extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='orders';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'reference' => 
  array (
    'name' => 'reference',
    'type' => 'S',
    'length' => '32',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'T',
    'length' => -1,
  ),
  'updated_on' => 
  array (
    'name' => 'updated_on',
    'type' => 'S',
    'length' => -1,
  ),
  'pay_money' => 
  array (
    'name' => 'pay_money',
    'type' => 'N',
    'length' => -1,
  ),
  'total_money' => 
  array (
    'name' => 'total_money',
    'type' => 'N',
    'length' => -1,
  ),
  'card_money' => 
  array (
    'name' => 'card_money',
    'type' => 'N',
    'length' => -1,
  ),
  'coin_money' => 
  array (
    'name' => 'coin_money',
    'type' => 'N',
    'length' => -1,
  ),
  'freight' => 
  array (
    'name' => 'freight',
    'type' => 'N',
    'length' => -1,
  ),
  'discount' => 
  array (
    'name' => 'discount',
    'type' => 'N',
    'length' => -1,
  ),
  'user_id' => 
  array (
    'name' => 'user_id',
    'type' => 'N',
    'length' => '11',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '25',
  ),
  'email' => 
  array (
    'name' => 'email',
    'type' => 'S',
    'length' => '100',
  ),
  'province' => 
  array (
    'name' => 'province',
    'type' => 'S',
    'length' => '25',
  ),
  'city' => 
  array (
    'name' => 'city',
    'type' => 'S',
    'length' => '25',
  ),
  'area' => 
  array (
    'name' => 'area',
    'type' => 'S',
    'length' => '30',
  ),
  'address' => 
  array (
    'name' => 'address',
    'type' => 'S',
    'length' => '150',
  ),
  'zip' => 
  array (
    'name' => 'zip',
    'type' => 'S',
    'length' => '25',
  ),
  'mobie' => 
  array (
    'name' => 'mobie',
    'type' => 'S',
    'length' => '25',
  ),
  'telephone' => 
  array (
    'name' => 'telephone',
    'type' => 'S',
    'length' => '25',
  ),
  'is_invoice' => 
  array (
    'name' => 'is_invoice',
    'type' => 'S',
    'length' => '1',
  ),
  'invoice_type' => 
  array (
    'name' => 'invoice_type',
    'type' => 'S',
    'length' => '1',
  ),
  'invoice_caty' => 
  array (
    'name' => 'invoice_caty',
    'type' => 'S',
    'length' => '2',
  ),
  'invoice_title' => 
  array (
    'name' => 'invoice_title',
    'type' => 'S',
    'length' => '100',
  ),
  'invoice_content' => 
  array (
    'name' => 'invoice_content',
    'type' => 'S',
    'length' => '25',
  ),
  'is_pay' => 
  array (
    'name' => 'is_pay',
    'type' => 'S',
    'length' => '1',
  ),
  'pay_date' => 
  array (
    'name' => 'pay_date',
    'type' => 'T',
    'length' => -1,
  ),
  'cancel_date' => 
  array (
    'name' => 'cancel_date',
    'type' => 'T',
    'length' => -1,
  ),
  'status' => 
  array (
    'name' => 'status',
    'type' => 'S',
    'length' => '1',
  ),
  'summary' => 
  array (
    'name' => 'summary',
    'type' => 'S',
    'length' => '254',
  ),
  'transfer' => 
  array (
    'name' => 'transfer',
    'type' => 'S',
    'length' => '2',
  ),
  'payment_method' => 
  array (
    'name' => 'payment_method',
    'type' => 'S',
    'length' => '2',
  ),
  'transfer_time' => 
  array (
    'name' => 'transfer_time',
    'type' => 'S',
    'length' => '2',
  ),
  'ip' => 
  array (
    'name' => 'ip',
    'type' => 'S',
    'length' => '15',
  ),
  'sesid' => 
  array (
    'name' => 'sesid',
    'type' => 'S',
    'length' => '30',
  ),
  'referer' => 
  array (
    'name' => 'referer',
    'type' => 'S',
    'length' => '200',
  ),
  'fromword' => 
  array (
    'name' => 'fromword',
    'type' => 'S',
    'length' => '100',
  ),
  'card_code' => 
  array (
    'name' => 'card_code',
    'type' => 'S',
    'length' => '32',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'reference'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setReference($value){
        $this->set('reference',$value);
        return $this;
    }
    /**
     * 获取属性:'reference'的值
     * 
     * @return string
     */
    public function getReference(){
        return $this->get('reference');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  date $value
     * 
     * @return Orders
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return date
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'updated_on'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setUpdatedOn($value){
        $this->set('updated_on',$value);
        return $this;
    }
    /**
     * 获取属性:'updated_on'的值
     * 
     * @return string
     */
    public function getUpdatedOn(){
        return $this->get('updated_on');
    }
        /**
     * 设置属性'pay_money'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setPayMoney($value){
        $this->set('pay_money',$value);
        return $this;
    }
    /**
     * 获取属性:'pay_money'的值
     * 
     * @return integer
     */
    public function getPayMoney(){
        return $this->get('pay_money');
    }
        /**
     * 设置属性'total_money'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setTotalMoney($value){
        $this->set('total_money',$value);
        return $this;
    }
    /**
     * 获取属性:'total_money'的值
     * 
     * @return integer
     */
    public function getTotalMoney(){
        return $this->get('total_money');
    }
        /**
     * 设置属性'card_money'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setCardMoney($value){
        $this->set('card_money',$value);
        return $this;
    }
    /**
     * 获取属性:'card_money'的值
     * 
     * @return integer
     */
    public function getCardMoney(){
        return $this->get('card_money');
    }
        /**
     * 设置属性'coin_money'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setCoinMoney($value){
        $this->set('coin_money',$value);
        return $this;
    }
    /**
     * 获取属性:'coin_money'的值
     * 
     * @return integer
     */
    public function getCoinMoney(){
        return $this->get('coin_money');
    }
        /**
     * 设置属性'freight'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setFreight($value){
        $this->set('freight',$value);
        return $this;
    }
    /**
     * 获取属性:'freight'的值
     * 
     * @return integer
     */
    public function getFreight(){
        return $this->get('freight');
    }
        /**
     * 设置属性'discount'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setDiscount($value){
        $this->set('discount',$value);
        return $this;
    }
    /**
     * 获取属性:'discount'的值
     * 
     * @return integer
     */
    public function getDiscount(){
        return $this->get('discount');
    }
        /**
     * 设置属性'user_id'的值
     *
     * @param  integer $value
     * 
     * @return Orders
     */
    public function setUserId($value){
        $this->set('user_id',$value);
        return $this;
    }
    /**
     * 获取属性:'user_id'的值
     * 
     * @return integer
     */
    public function getUserId(){
        return $this->get('user_id');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'email'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setEmail($value){
        $this->set('email',$value);
        return $this;
    }
    /**
     * 获取属性:'email'的值
     * 
     * @return string
     */
    public function getEmail(){
        return $this->get('email');
    }
        /**
     * 设置属性'province'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setProvince($value){
        $this->set('province',$value);
        return $this;
    }
    /**
     * 获取属性:'province'的值
     * 
     * @return string
     */
    public function getProvince(){
        return $this->get('province');
    }
        /**
     * 设置属性'city'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setCity($value){
        $this->set('city',$value);
        return $this;
    }
    /**
     * 获取属性:'city'的值
     * 
     * @return string
     */
    public function getCity(){
        return $this->get('city');
    }
        /**
     * 设置属性'area'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setArea($value){
        $this->set('area',$value);
        return $this;
    }
    /**
     * 获取属性:'area'的值
     * 
     * @return string
     */
    public function getArea(){
        return $this->get('area');
    }
        /**
     * 设置属性'address'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setAddress($value){
        $this->set('address',$value);
        return $this;
    }
    /**
     * 获取属性:'address'的值
     * 
     * @return string
     */
    public function getAddress(){
        return $this->get('address');
    }
        /**
     * 设置属性'zip'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setZip($value){
        $this->set('zip',$value);
        return $this;
    }
    /**
     * 获取属性:'zip'的值
     * 
     * @return string
     */
    public function getZip(){
        return $this->get('zip');
    }
        /**
     * 设置属性'mobie'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setMobie($value){
        $this->set('mobie',$value);
        return $this;
    }
    /**
     * 获取属性:'mobie'的值
     * 
     * @return string
     */
    public function getMobie(){
        return $this->get('mobie');
    }
        /**
     * 设置属性'telephone'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setTelephone($value){
        $this->set('telephone',$value);
        return $this;
    }
    /**
     * 获取属性:'telephone'的值
     * 
     * @return string
     */
    public function getTelephone(){
        return $this->get('telephone');
    }
        /**
     * 设置属性'is_invoice'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setIsInvoice($value){
        $this->set('is_invoice',$value);
        return $this;
    }
    /**
     * 获取属性:'is_invoice'的值
     * 
     * @return string
     */
    public function getIsInvoice(){
        return $this->get('is_invoice');
    }
        /**
     * 设置属性'invoice_type'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setInvoiceType($value){
        $this->set('invoice_type',$value);
        return $this;
    }
    /**
     * 获取属性:'invoice_type'的值
     * 
     * @return string
     */
    public function getInvoiceType(){
        return $this->get('invoice_type');
    }
        /**
     * 设置属性'invoice_caty'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setInvoiceCaty($value){
        $this->set('invoice_caty',$value);
        return $this;
    }
    /**
     * 获取属性:'invoice_caty'的值
     * 
     * @return string
     */
    public function getInvoiceCaty(){
        return $this->get('invoice_caty');
    }
        /**
     * 设置属性'invoice_title'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setInvoiceTitle($value){
        $this->set('invoice_title',$value);
        return $this;
    }
    /**
     * 获取属性:'invoice_title'的值
     * 
     * @return string
     */
    public function getInvoiceTitle(){
        return $this->get('invoice_title');
    }
        /**
     * 设置属性'invoice_content'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setInvoiceContent($value){
        $this->set('invoice_content',$value);
        return $this;
    }
    /**
     * 获取属性:'invoice_content'的值
     * 
     * @return string
     */
    public function getInvoiceContent(){
        return $this->get('invoice_content');
    }
        /**
     * 设置属性'is_pay'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setIsPay($value){
        $this->set('is_pay',$value);
        return $this;
    }
    /**
     * 获取属性:'is_pay'的值
     * 
     * @return string
     */
    public function getIsPay(){
        return $this->get('is_pay');
    }
        /**
     * 设置属性'pay_date'的值
     *
     * @param  date $value
     * 
     * @return Orders
     */
    public function setPayDate($value){
        $this->set('pay_date',$value);
        return $this;
    }
    /**
     * 获取属性:'pay_date'的值
     * 
     * @return date
     */
    public function getPayDate(){
        return $this->get('pay_date');
    }
        /**
     * 设置属性'cancel_date'的值
     *
     * @param  date $value
     * 
     * @return Orders
     */
    public function setCancelDate($value){
        $this->set('cancel_date',$value);
        return $this;
    }
    /**
     * 获取属性:'cancel_date'的值
     * 
     * @return date
     */
    public function getCancelDate(){
        return $this->get('cancel_date');
    }
        /**
     * 设置属性'status'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setStatus($value){
        $this->set('status',$value);
        return $this;
    }
    /**
     * 获取属性:'status'的值
     * 
     * @return string
     */
    public function getStatus(){
        return $this->get('status');
    }
        /**
     * 设置属性'summary'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setSummary($value){
        $this->set('summary',$value);
        return $this;
    }
    /**
     * 获取属性:'summary'的值
     * 
     * @return string
     */
    public function getSummary(){
        return $this->get('summary');
    }
        /**
     * 设置属性'transfer'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setTransfer($value){
        $this->set('transfer',$value);
        return $this;
    }
    /**
     * 获取属性:'transfer'的值
     * 
     * @return string
     */
    public function getTransfer(){
        return $this->get('transfer');
    }
        /**
     * 设置属性'payment_method'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setPaymentMethod($value){
        $this->set('payment_method',$value);
        return $this;
    }
    /**
     * 获取属性:'payment_method'的值
     * 
     * @return string
     */
    public function getPaymentMethod(){
        return $this->get('payment_method');
    }
        /**
     * 设置属性'transfer_time'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setTransferTime($value){
        $this->set('transfer_time',$value);
        return $this;
    }
    /**
     * 获取属性:'transfer_time'的值
     * 
     * @return string
     */
    public function getTransferTime(){
        return $this->get('transfer_time');
    }
        /**
     * 设置属性'ip'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setIp($value){
        $this->set('ip',$value);
        return $this;
    }
    /**
     * 获取属性:'ip'的值
     * 
     * @return string
     */
    public function getIp(){
        return $this->get('ip');
    }
        /**
     * 设置属性'sesid'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setSesid($value){
        $this->set('sesid',$value);
        return $this;
    }
    /**
     * 获取属性:'sesid'的值
     * 
     * @return string
     */
    public function getSesid(){
        return $this->get('sesid');
    }
        /**
     * 设置属性'referer'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setReferer($value){
        $this->set('referer',$value);
        return $this;
    }
    /**
     * 获取属性:'referer'的值
     * 
     * @return string
     */
    public function getReferer(){
        return $this->get('referer');
    }
        /**
     * 设置属性'fromword'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setFromword($value){
        $this->set('fromword',$value);
        return $this;
    }
    /**
     * 获取属性:'fromword'的值
     * 
     * @return string
     */
    public function getFromword(){
        return $this->get('fromword');
    }
        /**
     * 设置属性'card_code'的值
     *
     * @param  string $value
     * 
     * @return Orders
     */
    public function setCardCode($value){
        $this->set('card_code',$value);
        return $this;
    }
    /**
     * 获取属性:'card_code'的值
     * 
     * @return string
     */
    public function getCardCode(){
        return $this->get('card_code');
    }
    }
/**vim:sw=4 et ts=4 **/
?>