<?php
/**
 * Table:orders_data mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_OrdersData extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='orders_data';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'reference' => 
  array (
    'name' => 'reference',
    'type' => 'S',
    'length' => '32',
  ),
  'data' => 
  array (
    'name' => 'data',
    'type' => 'S',
    'length' => -1,
  ),
  'expire' => 
  array (
    'name' => 'expire',
    'type' => 'N',
    'length' => '10',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return OrdersData
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'reference'的值
     *
     * @param  string $value
     * 
     * @return OrdersData
     */
    public function setReference($value){
        $this->set('reference',$value);
        return $this;
    }
    /**
     * 获取属性:'reference'的值
     * 
     * @return string
     */
    public function getReference(){
        return $this->get('reference');
    }
        /**
     * 设置属性'data'的值
     *
     * @param  string $value
     * 
     * @return OrdersData
     */
    public function setData($value){
        $this->set('data',$value);
        return $this;
    }
    /**
     * 获取属性:'data'的值
     * 
     * @return string
     */
    public function getData(){
        return $this->get('data');
    }
        /**
     * 设置属性'expire'的值
     *
     * @param  integer $value
     * 
     * @return OrdersData
     */
    public function setExpire($value){
        $this->set('expire',$value);
        return $this;
    }
    /**
     * 获取属性:'expire'的值
     * 
     * @return integer
     */
    public function getExpire(){
        return $this->get('expire');
    }
    }
/**vim:sw=4 et ts=4 **/
?>