<?php
/**
 * Table:permission mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Permission extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='permission';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '4',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '50',
  ),
  'resource' => 
  array (
    'name' => 'resource',
    'type' => 'S',
    'length' => '50',
  ),
  'privilege' => 
  array (
    'name' => 'privilege',
    'type' => 'S',
    'length' => '100',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Permission
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return Permission
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'resource'的值
     *
     * @param  string $value
     * 
     * @return Permission
     */
    public function setResource($value){
        $this->set('resource',$value);
        return $this;
    }
    /**
     * 获取属性:'resource'的值
     * 
     * @return string
     */
    public function getResource(){
        return $this->get('resource');
    }
        /**
     * 设置属性'privilege'的值
     *
     * @param  string $value
     * 
     * @return Permission
     */
    public function setPrivilege($value){
        $this->set('privilege',$value);
        return $this;
    }
    /**
     * 获取属性:'privilege'的值
     * 
     * @return string
     */
    public function getPrivilege(){
        return $this->get('privilege');
    }
    }
/**vim:sw=4 et ts=4 **/
?>