<?php
/**
 * Table:postoffice mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Postoffice extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='postoffice';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'mailto' => 
  array (
    'name' => 'mailto',
    'type' => 'S',
    'length' => '50',
  ),
  'mailfrom' => 
  array (
    'name' => 'mailfrom',
    'type' => 'S',
    'length' => '50',
  ),
  'from_name' => 
  array (
    'name' => 'from_name',
    'type' => 'S',
    'length' => '50',
  ),
  'subject' => 
  array (
    'name' => 'subject',
    'type' => 'S',
    'length' => '100',
  ),
  'body' => 
  array (
    'name' => 'body',
    'type' => 'S',
    'length' => -1,
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Postoffice
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'mailto'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setMailto($value){
        $this->set('mailto',$value);
        return $this;
    }
    /**
     * 获取属性:'mailto'的值
     * 
     * @return string
     */
    public function getMailto(){
        return $this->get('mailto');
    }
        /**
     * 设置属性'mailfrom'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setMailfrom($value){
        $this->set('mailfrom',$value);
        return $this;
    }
    /**
     * 获取属性:'mailfrom'的值
     * 
     * @return string
     */
    public function getMailfrom(){
        return $this->get('mailfrom');
    }
        /**
     * 设置属性'from_name'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setFromName($value){
        $this->set('from_name',$value);
        return $this;
    }
    /**
     * 获取属性:'from_name'的值
     * 
     * @return string
     */
    public function getFromName(){
        return $this->get('from_name');
    }
        /**
     * 设置属性'subject'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setSubject($value){
        $this->set('subject',$value);
        return $this;
    }
    /**
     * 获取属性:'subject'的值
     * 
     * @return string
     */
    public function getSubject(){
        return $this->get('subject');
    }
        /**
     * 设置属性'body'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setBody($value){
        $this->set('body',$value);
        return $this;
    }
    /**
     * 获取属性:'body'的值
     * 
     * @return string
     */
    public function getBody(){
        return $this->get('body');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return Postoffice
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
    }
/**vim:sw=4 et ts=4 **/
?>