<?php
/**
 * Table:purchase mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Purchase extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='purchase';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'S',
    'length' => '11',
  ),
  'product_id' => 
  array (
    'name' => 'product_id',
    'type' => 'S',
    'length' => '11',
  ),
  'product_size' => 
  array (
    'name' => 'product_size',
    'type' => 'S',
    'length' => '10',
  ),
  'quantity' => 
  array (
    'name' => 'quantity',
    'type' => 'N',
    'length' => '4',
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'summary' => 
  array (
    'name' => 'summary',
    'type' => 'S',
    'length' => '200',
  ),
  'created_by' => 
  array (
    'name' => 'created_by',
    'type' => 'S',
    'length' => '11',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'T',
    'length' => -1,
  ),
  'published_by' => 
  array (
    'name' => 'published_by',
    'type' => 'S',
    'length' => '11',
  ),
  'published_on' => 
  array (
    'name' => 'published_on',
    'type' => 'T',
    'length' => -1,
  ),
  'status' => 
  array (
    'name' => 'status',
    'type' => 'S',
    'length' => '1',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return string
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'product_id'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setProductId($value){
        $this->set('product_id',$value);
        return $this;
    }
    /**
     * 获取属性:'product_id'的值
     * 
     * @return string
     */
    public function getProductId(){
        return $this->get('product_id');
    }
        /**
     * 设置属性'product_size'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setProductSize($value){
        $this->set('product_size',$value);
        return $this;
    }
    /**
     * 获取属性:'product_size'的值
     * 
     * @return string
     */
    public function getProductSize(){
        return $this->get('product_size');
    }
        /**
     * 设置属性'quantity'的值
     *
     * @param  integer $value
     * 
     * @return Purchase
     */
    public function setQuantity($value){
        $this->set('quantity',$value);
        return $this;
    }
    /**
     * 获取属性:'quantity'的值
     * 
     * @return integer
     */
    public function getQuantity(){
        return $this->get('quantity');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'summary'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setSummary($value){
        $this->set('summary',$value);
        return $this;
    }
    /**
     * 获取属性:'summary'的值
     * 
     * @return string
     */
    public function getSummary(){
        return $this->get('summary');
    }
        /**
     * 设置属性'created_by'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setCreatedBy($value){
        $this->set('created_by',$value);
        return $this;
    }
    /**
     * 获取属性:'created_by'的值
     * 
     * @return string
     */
    public function getCreatedBy(){
        return $this->get('created_by');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  date $value
     * 
     * @return Purchase
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return date
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'published_by'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setPublishedBy($value){
        $this->set('published_by',$value);
        return $this;
    }
    /**
     * 获取属性:'published_by'的值
     * 
     * @return string
     */
    public function getPublishedBy(){
        return $this->get('published_by');
    }
        /**
     * 设置属性'published_on'的值
     *
     * @param  date $value
     * 
     * @return Purchase
     */
    public function setPublishedOn($value){
        $this->set('published_on',$value);
        return $this;
    }
    /**
     * 获取属性:'published_on'的值
     * 
     * @return date
     */
    public function getPublishedOn(){
        return $this->get('published_on');
    }
        /**
     * 设置属性'status'的值
     *
     * @param  string $value
     * 
     * @return Purchase
     */
    public function setStatus($value){
        $this->set('status',$value);
        return $this;
    }
    /**
     * 获取属性:'status'的值
     * 
     * @return string
     */
    public function getStatus(){
        return $this->get('status');
    }
    }
/**vim:sw=4 et ts=4 **/
?>