<?php
/**
 * Table:ratings mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Ratings extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='ratings';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'S',
    'length' => '11',
  ),
  'target_id' => 
  array (
    'name' => 'target_id',
    'type' => 'S',
    'length' => '11',
  ),
  'target_title' => 
  array (
    'name' => 'target_title',
    'type' => 'S',
    'length' => '100',
  ),
  'point' => 
  array (
    'name' => 'point',
    'type' => 'N',
    'length' => '2',
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
  'ip' => 
  array (
    'name' => 'ip',
    'type' => 'S',
    'length' => '40',
  ),
  'username' => 
  array (
    'name' => 'username',
    'type' => 'S',
    'length' => '50',
  ),
  'userid' => 
  array (
    'name' => 'userid',
    'type' => 'N',
    'length' => '10',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return string
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'target_id'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setTargetId($value){
        $this->set('target_id',$value);
        return $this;
    }
    /**
     * 获取属性:'target_id'的值
     * 
     * @return string
     */
    public function getTargetId(){
        return $this->get('target_id');
    }
        /**
     * 设置属性'target_title'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setTargetTitle($value){
        $this->set('target_title',$value);
        return $this;
    }
    /**
     * 获取属性:'target_title'的值
     * 
     * @return string
     */
    public function getTargetTitle(){
        return $this->get('target_title');
    }
        /**
     * 设置属性'point'的值
     *
     * @param  integer $value
     * 
     * @return Ratings
     */
    public function setPoint($value){
        $this->set('point',$value);
        return $this;
    }
    /**
     * 获取属性:'point'的值
     * 
     * @return integer
     */
    public function getPoint(){
        return $this->get('point');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'ip'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setIp($value){
        $this->set('ip',$value);
        return $this;
    }
    /**
     * 获取属性:'ip'的值
     * 
     * @return string
     */
    public function getIp(){
        return $this->get('ip');
    }
        /**
     * 设置属性'username'的值
     *
     * @param  string $value
     * 
     * @return Ratings
     */
    public function setUsername($value){
        $this->set('username',$value);
        return $this;
    }
    /**
     * 获取属性:'username'的值
     * 
     * @return string
     */
    public function getUsername(){
        return $this->get('username');
    }
        /**
     * 设置属性'userid'的值
     *
     * @param  integer $value
     * 
     * @return Ratings
     */
    public function setUserid($value){
        $this->set('userid',$value);
        return $this;
    }
    /**
     * 获取属性:'userid'的值
     * 
     * @return integer
     */
    public function getUserid(){
        return $this->get('userid');
    }
    }
/**vim:sw=4 et ts=4 **/
?>