<?php
/**
 * Table:search mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Search extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='search';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '25',
  ),
  'ref_count' => 
  array (
    'name' => 'ref_count',
    'type' => 'N',
    'length' => '4',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Search
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return Search
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'ref_count'的值
     *
     * @param  integer $value
     * 
     * @return Search
     */
    public function setRefCount($value){
        $this->set('ref_count',$value);
        return $this;
    }
    /**
     * 获取属性:'ref_count'的值
     * 
     * @return integer
     */
    public function getRefCount(){
        return $this->get('ref_count');
    }
    }
/**vim:sw=4 et ts=4 **/
?>