<?php
/**
 * Table:sort mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Sort extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='sort';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '4',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'S',
    'length' => '25',
  ),
  'cnname' => 
  array (
    'name' => 'cnname',
    'type' => 'S',
    'length' => '100',
  ),
  'enname' => 
  array (
    'name' => 'enname',
    'type' => 'S',
    'length' => '100',
  ),
  'slug' => 
  array (
    'name' => 'slug',
    'type' => 'S',
    'length' => '200',
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
  'type' => 
  array (
    'name' => 'type',
    'type' => 'S',
    'length' => '1',
  ),
  'updated_on' => 
  array (
    'name' => 'updated_on',
    'type' => 'S',
    'length' => -1,
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Sort
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'name'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setName($value){
        $this->set('name',$value);
        return $this;
    }
    /**
     * 获取属性:'name'的值
     * 
     * @return string
     */
    public function getName(){
        return $this->get('name');
    }
        /**
     * 设置属性'cnname'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setCnname($value){
        $this->set('cnname',$value);
        return $this;
    }
    /**
     * 获取属性:'cnname'的值
     * 
     * @return string
     */
    public function getCnname(){
        return $this->get('cnname');
    }
        /**
     * 设置属性'enname'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setEnname($value){
        $this->set('enname',$value);
        return $this;
    }
    /**
     * 获取属性:'enname'的值
     * 
     * @return string
     */
    public function getEnname(){
        return $this->get('enname');
    }
        /**
     * 设置属性'slug'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setSlug($value){
        $this->set('slug',$value);
        return $this;
    }
    /**
     * 获取属性:'slug'的值
     * 
     * @return string
     */
    public function getSlug(){
        return $this->get('slug');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'type'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setType($value){
        $this->set('type',$value);
        return $this;
    }
    /**
     * 获取属性:'type'的值
     * 
     * @return string
     */
    public function getType(){
        return $this->get('type');
    }
        /**
     * 设置属性'updated_on'的值
     *
     * @param  string $value
     * 
     * @return Sort
     */
    public function setUpdatedOn($value){
        $this->set('updated_on',$value);
        return $this;
    }
    /**
     * 获取属性:'updated_on'的值
     * 
     * @return string
     */
    public function getUpdatedOn(){
        return $this->get('updated_on');
    }
    }
/**vim:sw=4 et ts=4 **/
?>