<?php
/**
 * Table:store mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Store extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='store';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'title' => 
  array (
    'name' => 'title',
    'type' => 'S',
    'length' => '200',
  ),
  'content' => 
  array (
    'name' => 'content',
    'type' => 'S',
    'length' => -1,
  ),
  'address' => 
  array (
    'name' => 'address',
    'type' => 'S',
    'length' => '200',
  ),
  'service' => 
  array (
    'name' => 'service',
    'type' => 'S',
    'length' => '200',
  ),
  'hours' => 
  array (
    'name' => 'hours',
    'type' => 'S',
    'length' => '100',
  ),
  'payment' => 
  array (
    'name' => 'payment',
    'type' => 'S',
    'length' => '100',
  ),
  'consumer_card' => 
  array (
    'name' => 'consumer_card',
    'type' => 'S',
    'length' => '255',
  ),
  'avg_money' => 
  array (
    'name' => 'avg_money',
    'type' => 'N',
    'length' => -1,
  ),
  'catcode' => 
  array (
    'name' => 'catcode',
    'type' => 'S',
    'length' => '25',
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
  'is_tax' => 
  array (
    'name' => 'is_tax',
    'type' => 'S',
    'length' => '1',
  ),
  'has_new' => 
  array (
    'name' => 'has_new',
    'type' => 'S',
    'length' => '1',
  ),
  'total' => 
  array (
    'name' => 'total',
    'type' => 'N',
    'length' => '4',
  ),
  'rest_num' => 
  array (
    'name' => 'rest_num',
    'type' => 'N',
    'length' => '4',
  ),
  'stick' => 
  array (
    'name' => 'stick',
    'type' => 'S',
    'length' => '1',
  ),
  'version' => 
  array (
    'name' => 'version',
    'type' => 'S',
    'length' => '1',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Store
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'title'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setTitle($value){
        $this->set('title',$value);
        return $this;
    }
    /**
     * 获取属性:'title'的值
     * 
     * @return string
     */
    public function getTitle(){
        return $this->get('title');
    }
        /**
     * 设置属性'content'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setContent($value){
        $this->set('content',$value);
        return $this;
    }
    /**
     * 获取属性:'content'的值
     * 
     * @return string
     */
    public function getContent(){
        return $this->get('content');
    }
        /**
     * 设置属性'address'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setAddress($value){
        $this->set('address',$value);
        return $this;
    }
    /**
     * 获取属性:'address'的值
     * 
     * @return string
     */
    public function getAddress(){
        return $this->get('address');
    }
        /**
     * 设置属性'service'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setService($value){
        $this->set('service',$value);
        return $this;
    }
    /**
     * 获取属性:'service'的值
     * 
     * @return string
     */
    public function getService(){
        return $this->get('service');
    }
        /**
     * 设置属性'hours'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setHours($value){
        $this->set('hours',$value);
        return $this;
    }
    /**
     * 获取属性:'hours'的值
     * 
     * @return string
     */
    public function getHours(){
        return $this->get('hours');
    }
        /**
     * 设置属性'payment'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setPayment($value){
        $this->set('payment',$value);
        return $this;
    }
    /**
     * 获取属性:'payment'的值
     * 
     * @return string
     */
    public function getPayment(){
        return $this->get('payment');
    }
        /**
     * 设置属性'consumer_card'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setConsumerCard($value){
        $this->set('consumer_card',$value);
        return $this;
    }
    /**
     * 获取属性:'consumer_card'的值
     * 
     * @return string
     */
    public function getConsumerCard(){
        return $this->get('consumer_card');
    }
        /**
     * 设置属性'avg_money'的值
     *
     * @param  integer $value
     * 
     * @return Store
     */
    public function setAvgMoney($value){
        $this->set('avg_money',$value);
        return $this;
    }
    /**
     * 获取属性:'avg_money'的值
     * 
     * @return integer
     */
    public function getAvgMoney(){
        return $this->get('avg_money');
    }
        /**
     * 设置属性'catcode'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setCatcode($value){
        $this->set('catcode',$value);
        return $this;
    }
    /**
     * 获取属性:'catcode'的值
     * 
     * @return string
     */
    public function getCatcode(){
        return $this->get('catcode');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
        /**
     * 设置属性'is_tax'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setIsTax($value){
        $this->set('is_tax',$value);
        return $this;
    }
    /**
     * 获取属性:'is_tax'的值
     * 
     * @return string
     */
    public function getIsTax(){
        return $this->get('is_tax');
    }
        /**
     * 设置属性'has_new'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setHasNew($value){
        $this->set('has_new',$value);
        return $this;
    }
    /**
     * 获取属性:'has_new'的值
     * 
     * @return string
     */
    public function getHasNew(){
        return $this->get('has_new');
    }
        /**
     * 设置属性'total'的值
     *
     * @param  integer $value
     * 
     * @return Store
     */
    public function setTotal($value){
        $this->set('total',$value);
        return $this;
    }
    /**
     * 获取属性:'total'的值
     * 
     * @return integer
     */
    public function getTotal(){
        return $this->get('total');
    }
        /**
     * 设置属性'rest_num'的值
     *
     * @param  integer $value
     * 
     * @return Store
     */
    public function setRestNum($value){
        $this->set('rest_num',$value);
        return $this;
    }
    /**
     * 获取属性:'rest_num'的值
     * 
     * @return integer
     */
    public function getRestNum(){
        return $this->get('rest_num');
    }
        /**
     * 设置属性'stick'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setStick($value){
        $this->set('stick',$value);
        return $this;
    }
    /**
     * 获取属性:'stick'的值
     * 
     * @return string
     */
    public function getStick(){
        return $this->get('stick');
    }
        /**
     * 设置属性'version'的值
     *
     * @param  string $value
     * 
     * @return Store
     */
    public function setVersion($value){
        $this->set('version',$value);
        return $this;
    }
    /**
     * 获取属性:'version'的值
     * 
     * @return string
     */
    public function getVersion(){
        return $this->get('version');
    }
    }
/**vim:sw=4 et ts=4 **/
?>