<?php
/**
 * Table:user mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_User extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='user';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '11',
  ),
  'account' => 
  array (
    'name' => 'account',
    'type' => 'S',
    'length' => '100',
  ),
  'password' => 
  array (
    'name' => 'password',
    'type' => 'S',
    'length' => '64',
  ),
  'role_id' => 
  array (
    'name' => 'role_id',
    'type' => 'N',
    'length' => '4',
  ),
  'level' => 
  array (
    'name' => 'level',
    'type' => 'S',
    'length' => '1',
  ),
  'username' => 
  array (
    'name' => 'username',
    'type' => 'S',
    'length' => '30',
  ),
  'sex' => 
  array (
    'name' => 'sex',
    'type' => 'S',
    'length' => '20',
  ),
  'activation' => 
  array (
    'name' => 'activation',
    'type' => 'S',
    'length' => '64',
  ),
  'point' => 
  array (
    'name' => 'point',
    'type' => 'N',
    'length' => -1,
  ),
  'created_on' => 
  array (
    'name' => 'created_on',
    'type' => 'S',
    'length' => -1,
  ),
  'updated_on' => 
  array (
    'name' => 'updated_on',
    'type' => 'T',
    'length' => -1,
  ),
  'lasted_on' => 
  array (
    'name' => 'lasted_on',
    'type' => 'T',
    'length' => -1,
  ),
  'is_reality' => 
  array (
    'name' => 'is_reality',
    'type' => 'S',
    'length' => '1',
  ),
  'state' => 
  array (
    'name' => 'state',
    'type' => 'S',
    'length' => '1',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return User
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'account'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setAccount($value){
        $this->set('account',$value);
        return $this;
    }
    /**
     * 获取属性:'account'的值
     * 
     * @return string
     */
    public function getAccount(){
        return $this->get('account');
    }
        /**
     * 设置属性'password'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setPassword($value){
        $this->set('password',$value);
        return $this;
    }
    /**
     * 获取属性:'password'的值
     * 
     * @return string
     */
    public function getPassword(){
        return $this->get('password');
    }
        /**
     * 设置属性'role_id'的值
     *
     * @param  integer $value
     * 
     * @return User
     */
    public function setRoleId($value){
        $this->set('role_id',$value);
        return $this;
    }
    /**
     * 获取属性:'role_id'的值
     * 
     * @return integer
     */
    public function getRoleId(){
        return $this->get('role_id');
    }
        /**
     * 设置属性'level'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setLevel($value){
        $this->set('level',$value);
        return $this;
    }
    /**
     * 获取属性:'level'的值
     * 
     * @return string
     */
    public function getLevel(){
        return $this->get('level');
    }
        /**
     * 设置属性'username'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setUsername($value){
        $this->set('username',$value);
        return $this;
    }
    /**
     * 获取属性:'username'的值
     * 
     * @return string
     */
    public function getUsername(){
        return $this->get('username');
    }
        /**
     * 设置属性'sex'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setSex($value){
        $this->set('sex',$value);
        return $this;
    }
    /**
     * 获取属性:'sex'的值
     * 
     * @return string
     */
    public function getSex(){
        return $this->get('sex');
    }
        /**
     * 设置属性'activation'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setActivation($value){
        $this->set('activation',$value);
        return $this;
    }
    /**
     * 获取属性:'activation'的值
     * 
     * @return string
     */
    public function getActivation(){
        return $this->get('activation');
    }
        /**
     * 设置属性'point'的值
     *
     * @param  integer $value
     * 
     * @return User
     */
    public function setPoint($value){
        $this->set('point',$value);
        return $this;
    }
    /**
     * 获取属性:'point'的值
     * 
     * @return integer
     */
    public function getPoint(){
        return $this->get('point');
    }
        /**
     * 设置属性'created_on'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setCreatedOn($value){
        $this->set('created_on',$value);
        return $this;
    }
    /**
     * 获取属性:'created_on'的值
     * 
     * @return string
     */
    public function getCreatedOn(){
        return $this->get('created_on');
    }
        /**
     * 设置属性'updated_on'的值
     *
     * @param  date $value
     * 
     * @return User
     */
    public function setUpdatedOn($value){
        $this->set('updated_on',$value);
        return $this;
    }
    /**
     * 获取属性:'updated_on'的值
     * 
     * @return date
     */
    public function getUpdatedOn(){
        return $this->get('updated_on');
    }
        /**
     * 设置属性'lasted_on'的值
     *
     * @param  date $value
     * 
     * @return User
     */
    public function setLastedOn($value){
        $this->set('lasted_on',$value);
        return $this;
    }
    /**
     * 获取属性:'lasted_on'的值
     * 
     * @return date
     */
    public function getLastedOn(){
        return $this->get('lasted_on');
    }
        /**
     * 设置属性'is_reality'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setIsReality($value){
        $this->set('is_reality',$value);
        return $this;
    }
    /**
     * 获取属性:'is_reality'的值
     * 
     * @return string
     */
    public function getIsReality(){
        return $this->get('is_reality');
    }
        /**
     * 设置属性'state'的值
     *
     * @param  string $value
     * 
     * @return User
     */
    public function setState($value){
        $this->set('state',$value);
        return $this;
    }
    /**
     * 获取属性:'state'的值
     * 
     * @return string
     */
    public function getState(){
        return $this->get('state');
    }
    }
/**vim:sw=4 et ts=4 **/
?>