<?php
/**
 * Table:xoption mapping class 
 * 
 * This class is auto generated by gen-model task
 */
abstract class Common_Model_Table_Xoption extends Anole_ActiveRecord_Base {
    
    /**
     * mapping table name
     * 
     * @var string
     */
    protected $_table_name='xoption';
    
    /**
     * table fields meta list
     * 
     * @var array
     */
    protected $_attributes = array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'N',
    'length' => '4',
  ),
  'option_name' => 
  array (
    'name' => 'option_name',
    'type' => 'S',
    'length' => '64',
  ),
  'option_value' => 
  array (
    'name' => 'option_value',
    'type' => 'S',
    'length' => -1,
  ),
  'autoload' => 
  array (
    'name' => 'autoload',
    'type' => 'S',
    'length' => '20',
  ),
);
    
        /**
     * 设置属性'id'的值
     *
     * @param  integer $value
     * 
     * @return Xoption
     */
    public function setId($value){
        $this->set('id',$value);
        return $this;
    }
    /**
     * 获取属性:'id'的值
     * 
     * @return integer
     */
    public function getId(){
        return $this->get('id');
    }
        /**
     * 设置属性'option_name'的值
     *
     * @param  string $value
     * 
     * @return Xoption
     */
    public function setOptionName($value){
        $this->set('option_name',$value);
        return $this;
    }
    /**
     * 获取属性:'option_name'的值
     * 
     * @return string
     */
    public function getOptionName(){
        return $this->get('option_name');
    }
        /**
     * 设置属性'option_value'的值
     *
     * @param  string $value
     * 
     * @return Xoption
     */
    public function setOptionValue($value){
        $this->set('option_value',$value);
        return $this;
    }
    /**
     * 获取属性:'option_value'的值
     * 
     * @return string
     */
    public function getOptionValue(){
        return $this->get('option_value');
    }
        /**
     * 设置属性'autoload'的值
     *
     * @param  string $value
     * 
     * @return Xoption
     */
    public function setAutoload($value){
        $this->set('autoload',$value);
        return $this;
    }
    /**
     * 获取属性:'autoload'的值
     * 
     * @return string
     */
    public function getAutoload(){
        return $this->get('autoload');
    }
    }
/**vim:sw=4 et ts=4 **/
?>