<?php
/**
 * Model Common_Model_Addbooks
 * 
 * generated by gen-model task.
 */
class Common_Model_Addbooks extends Common_Model_Table_Addbooks {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Addbooks
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function validate(){
        $ok = true;
        if ($this->isNew()){
            $required = array('name','mobie','user_id','address');
        }else{
            $required = array('id');
        }
        if(!$this->validateRequird($required)){
            self::warn('fields validate error!', __METHOD__);
            $ok = false;
        }
            
        return $ok; 
    }
    
    /**
     * 新建一个地址薄
     * 
     * @param array $add_ary
     * @return bool
     */
    public function createAddress($user_id,$add_ary){
        if(empty($add_ary)){
            return false;
        }
        $name = isset($add_ary['name'])?$add_ary['name']:null;
        $mobie = isset($add_ary['mobie'])?$add_ary['mobie']:null;
        $address = isset($add_ary['address'])?$add_ary['address']:null;
        if(empty($user_id) || empty($name) || empty($mobie) || empty($address)){
            self::warn("addbooks and condition not enough", __METHOD__);
            return false;
        }
        //查找是否已存在某地址
        
        if($this->countIf('user_id=? AND name=?', array($user_id,$name))){
            return true;
        }
        //新添加
        $this->setIsNew(true);
        $this->setId(null);
        
        $this->setMobie($mobie);
        $this->setTelephone(isset($add_ary['telephone']) ? $add_ary['telephone'] : null);
        $this->setUserId($user_id);
        $this->setName($name);
        $this->setProvince(isset($add_ary['province'])?$add_ary['province']:null);
        $this->setCity(isset($add_ary['city'])?$add_ary['city']:null);
        $this->setArea(isset($add_ary['area'])?$add_ary['area']:null);
        $this->setAddress($address);
        $this->setZip(isset($add_ary['zip'])?$add_ary['zip']:null);
        $this->setEmail(isset($add_ary['email'])?$add_ary['email']:null);
        
        try{
            $this->save();
        }catch(Anole_ActiveRecord_Exception $e){
            self::warn("create addbook and failed,skip", __METHOD__);
        }
        return true;
    }
}
/**vim:sw=4 et ts=4 **/
?>