<?php
/**
 * Model Common_Model_Advertise
 * 
 * generated by gen-model task.
 */
class Common_Model_Advertise extends Common_Model_Table_Advertise {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array(
        'thumb'=>'_getThumb'
    );
    //正常显示状态
    const CHECKED_STATE = 1;
    /**
     * @return Common_Model_Advertise
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    /**
     * afterDestroy事件
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#afterDestroy()
     */
    public function afterDestroy(){
    	//清除关联的附件
    	$id = $this->getId();
    	$asset_type = Common_Model_Constant::ADVERTISE;
    	
    	self::debug("Delete belong asset parent_id[$id]、parent_type[$asset_type].", __METHOD__);
    	
    	$asset = new Common_Model_Asset();
    	$condition = 'parent_id=? AND parent_type=?';
    	$vars = array($id,$asset_type);
    	$asset->destroyAll($condition,$vars);
    	unset($asset);
    }
    
    /**
     * 获取广告
     * 
     * @return string
     */
    protected function _getThumb(){
        $type = Common_Model_Constant::ADVERTISE;
        if(is_null($id)){
            $id = $this->getId();
        }
        if(empty($id)){
            self::warn("get ad picture failed and id is Null!", __METHOD__);
            return null;
        }
        $asset = new Common_Model_Asset();
        $asset->fetchAssetList($id,$type);
        self::debug("get advertise count:".$asset->count(), __METHOD__);
        if($asset->count()){
            return Common_Util_Storage::getAssetUrl(Common_Model_Constant::ADVERTISE_DOMAIN,$asset->_result[0]['path']);
        }
        return null;
    }
}
/**vim:sw=4 et ts=4 **/
?>