<?php
/**
 * Model Common_Model_Article
 * 
 * generated by gen-model task.
 */
class Common_Model_Article extends Common_Model_Table_Article {
    
    //关系映射表
    protected $_relation_map = array(
        //所属栏目
        'sorts'=>array(
            'type'=>self::HAS_AND_BELONGS_TO_MANY,
            'class'=>'Common_Model_Sort',
            'this_foreign_key'=>'article_id',
            'other_foreign_key'=>'sort_id',
            'join_table'=>'article_sort'
        ),
        //附件
        'assets'=>array(
            'type'=>self::HAS_MANY,
            'class'=>'Common_Model_Asset',
            'foreign_key'=>'parent_id',
            'options'=>array(
                 'condition'=>'parent_type=?',
                 'vars'=>array(Common_Model_Constant::ARTICLE_SOURCE)
            )
        ),
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array(
        'sort_ids'=>'_getBelongSort'
    );
    /**
     * 稿件库状态
     * 
     * @var int
     */
    const CHECKED_STATUS = 1;
    /**
     * 草稿箱状态
     * 
     * @var int
     */
    const DRAFT_STATUS = 0;
    /**
     * 垃圾箱状态
     * 
     * @var int
     */
    const DUSTBIN_STATUS = -1;
    /**
     * 资讯标识
     * 
     * @var int
     */
    const ARTICLE_TYPE = 1;
    /**
     * 专题标识
     * 
     * @var int
     */
    const TOPIC_TYPE = 2;
    /**
     * 英文版类型
     * 
     * @var string
     */
    const EN_VERSION = 2;
    
    private $_belongs_sorts = array();
    /**
     * @return Common_Model_Article
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function beforeValidation(){
        if($this->isNew()){
            $this->setCreatedOn(date('Y-m-d H:i:s'));
            $this->setStatus(self::DRAFT_STATUS);
            
            $type = $this->getType();
	        if($type == self::TOPIC_TYPE){
	            $name = $this->getName();
	            if(empty($name)){
	                $this->pushValidateError('topic name is NULL');
	                return False;
	            }
	        }
        }
        return true;
    }
    /**
     * validate验证
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#validate()
     */
    public function validate(){
        if($this->isNew()){
            $fields = array('title','excerpt');   
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            return False;
        }
        return true;
    }
    /**
     * afterValidation事件
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#afterValidation()
     */
    public function afterValidation(){
    	$status = $this->getStatus();
    	if($status == self::CHECKED_STATUS){
    		$admin_id = Anole_Util_Cookie::getAdminID();
    		$this->setPublishedOn(Common_Util_Date::getNow());
    		$this->setPublishedBy($admin_id);
    	}
    }
    
    public function beforeSave(){
        //检查所属栏目
        $this->_validateBelongSort();	
    }
    /**
     * after create 事件 (non-PHPdoc)
     */
    public function afterCreate(){}
    /**
     * after save (non-PHPdoc)
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#afterSave()
     */
    public function afterSave(){}
    
    /**
     * afterDestroy事件
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#afterDestroy()
     */
    public function afterDestroy(){
        $id = $this->getId();
        
        if(!empty($id)){
            self::debug("re article[$id] assets..", __METHOD__);
            
            $asset = new Common_Model_Asset();
            if(is_array($id)){
                foreach($id as $pid){
                    $condition = 'parent_id=? AND parent_type=?';
                    $vars = array($pid,Common_Model_Constant::ARTICLE_SOURCE);
                    
                    //删除文章的附件
                    $asset->destroyAll($condition,$vars);
                }
            }else{
                $condition = 'parent_id=? AND parent_type=?';
                $vars = array($id,Common_Model_Constant::ARTICLE_SOURCE);
                
                //删除文章的附件
                $asset->destroyAll($condition,$vars);
            }
            
            unset($asset);
            
            
            //清除关联表数据
           $dsql = 'DELETE FROM `article_sort` WHERE article_id=?';
           $this->getDba()->execute($dsql,array($id));
           
           //清除相关的meta
           $meta = new Common_Model_Meta();
           $meta->destroyAll('owner_id=? AND domain=?', array($id,Common_Model_Constant::ARTICLE_DOMAIN));
           
           unset($meta);
        }
       
        return true;
    }
    /**
     * 验证是否可以验证专题
     * 
     * @return bool
     */
    protected function _makeTopicDir($name=null){
    	if(is_null($name)){
    		$name = $this->getName();
    	}
    	if(empty($name)){
    		throw new Common_Model_Exception('topic name is NULL');
    		return false;
    	}
    	$topic_path = Common_Util_Storage::getTopicPath($name);
    	if(!file_exists($topic_path)){
    		Anole_Util_File::mk($topic_path);
    	}
    	
    	return true;
    }
    
    /**
     * 验证是否有需要更新的栏目
     * 
     * @return Common_Model_Article
     */
    protected function _validateBelongSort(){
    	if(empty($this->_belongs_sorts)){
    		return;
    	}
    	foreach($this->_belongs_sorts as $item){
    		$this->addRelationModelData('sorts', $item);
    	}
    	//reset empty
    	$this->_belongs_sorts = array();
    	return $this;
    }
    /**
     * 添加所属栏目
     * 
     * @param int $sort_id
     * @return Common_Model_Article
     */
    public function addBelongSorts($sort_id){
    	$this->_belongs_sorts[] = array('sort_id'=>$sort_id);
    	return $this;
    }
    /**
     * 获取所属的栏目Id列表
     * 
     * @return array
     */
    protected function _getBelongSort(){
    	$belong_ids = array();
    	$id = $this->getId();
    	if(empty($id)){
    		return $belong_ids;
    	}
    	$sorts = $this->findRelationModel('sorts',array(),$id);
    	$max = $sorts->count();
    	if($max > 0){
    		for($i=0;$i<$max;$i++){
    			$belong_ids[] = $sorts[$i]['sort_id'];
    		}
    	}
    	return $belong_ids;
    }
    /**
     * 获取资讯的所有附件
     * 
     * @param int $id
     * @return array
     */
    public function fetchArticleAssets($id=null){
    	$asset = new Common_Model_Asset();
        
        $options = array(
           'condition'=>'parent_id=? AND parent_type=?',
           'order'=>'created_on DESC',
           'vars'=>array($id, Common_Model_Constant::ARTICLE_SOURCE)
        );
        
        $assets = $asset->find($options)->getResultArray();
        if(!empty($assets)){
            for($i=0;$i<count($assets);$i++){
                $assets[$i]['url'] = Common_Util_Storage::getAssetUrl(Common_Model_Constant::ARTICLE_DOMAIN,$assets[$i]['path']);
            }
        }
        
        return $assets;
    }
    
    /**
     * 查找匹配指定条件的记录的数量，如果没有匹配则返回0
     *
     * @param string $condition
     * @param array $vars
     * @param string $table
     * @param string $joins
     * 
     * @return int
     */
    public function countIfRelated($condition=null,$vars=array(),$joins=null,$table=null){
        if(is_null($table)){
            $table = $this->tablelize();
        }else{
            $table = $this->tablelize($table);
        }
        $sql = 'SELECT COUNT(*) AS cnt FROM `'.$table.'`';
        
        if($joins){
            $sql .= " $joins "; 
        }
        if(!empty($condition)){
            $sql .= " WHERE $condition";
        }
        try{
            $rows = self::getDba()->query($sql,1,1,$vars);
        }catch(Anole_Dba_Exception $e){
            self::warn("count data error:".$e->getMessage(), __METHOD__);
        }
        return $rows[0]['cnt'];
    }
}
/**vim:sw=4 et ts=4 **/
?>