<?php
/**
 * Model Common_Model_Comment
 * 
 * generated by gen-model task.
 */
class Common_Model_Comment extends Common_Model_Table_Comment {
    /**
     * 用户评论类型
     * @var int
     */
	const COMMENT_TYPE = 1;
	/**
	 * 用户留言类型
	 * @var int
	 */
	const MESSAGE_TYPE = 2;
	/**
	 * 用户反馈类型
	 * @var int
	 */
	const FEEKBACK_TYPE = 3;
	
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Comment
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    /**
     * validate验证
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#validate()
     */
    public function validate(){
        if($this->isNew()){
            $fields = array('target_id','content');
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            return false;
        }
        return true;
    }
    /**
     * afterSave事件
     * @see src/Anole/ActiveRecord/Anole_ActiveRecord_Base#afterSave()
     */
    public function afterSave(){
    	$type = $this->getType();
    	if($type == 1){
    		$target_id = $this->getTargetId();
    		$this->_updateProductCommentCount($target_id);
    	}
    }
    /**
     * 更新产品评论数
     * 
     * @return void
     */
    protected function _updateProductCommentCount($target_id){
    	$update_sql = 'UPDATE `product` SET `coment_count`=`coment_count`+1 WHERE id=?';
    	$this->getDba()->execute($update_sql,array($target_id));
    }
    
    
}
/**vim:sw=4 et ts=4 **/
?>