<?php
/**
 * Model Common_Model_Emailing
 * 
 * generated by gen-model task.
 */
class Common_Model_Emailing extends Common_Model_Table_Emailing {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Emailing
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function validate(){
        if($this->isNew()){
            $fields = array('email');   
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            self::warn("fields validate failed!", __METHOD__);
            return false;
        }
        if($this->isNew()){
        	$this->_validateEmailExist();
        }
        return true;
    }
    
    protected function _validateEmailExist($email=null){
    	if(is_null($email)){
    		$email = $this->getEmail();
    	}
    	if(empty($email)){
    		throw new Common_Model_Exception('Email地址为空');
    	}
    	$cnt = $this->countIf('email=?',array($email));
    	if($cnt == 0){
    		return true;
    	}else{
    		throw new Common_Model_Exception("Email[$email]已存在，您不需要重复提交！");
    	}
    	return false;
    }
    
}
/**vim:sw=4 et ts=4 **/
?>