<?php
/**
 * Model Common_Model_Favorite
 * 
 * generated by gen-model task.
 */
class Common_Model_Favorite extends Common_Model_Table_Favorite {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Favorite
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function validation(){
        if($this->isNew()){
            $fields = array('user_id','product_id');   
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            return False;
        }
    }
    /**
     * 新建数据完成后的事件
     * 
     * @see Anole/ActiveRecord/Anole_ActiveRecord_Base#afterCreate()
     */
    public function afterCreate(){
    	//产品的收藏次数+1
        $product_id = $this->getProductId();
        Common_Event_Update::updateProductCount($product_id,'fav_count');
        
        return true;
    }
    
}
/**vim:sw=4 et ts=4 **/
?>