<?php
/**
 * Model Common_Model_Goods
 * 
 * generated by gen-model task.
 */
class Common_Model_Goods extends Common_Model_Table_Goods {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Goods
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
}
/**vim:sw=4 et ts=4 **/
?>