<?php
/**
 * Model Common_Model_OrdersData
 * 
 * generated by gen-model task.
 */
class Common_Model_OrdersData extends Common_Model_Table_OrdersData {
    
	const EXPIRE_TIME = 36000;
	
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_OrdersData
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function beforeValidation(){
        $this->setExpire(time()+self::EXPIRE_TIME);
    }
    
    public function afterSave(){
        $this->_clearExpiredData();
    }
    
    /**
     * 验证是否存在某个订单的临时信息
     * 
     * @param string $reference
     * @return bool
     */
    public function validateExistReference($reference){
        if(is_null($reference)){
            $reference = $this->getReference();
        }
        if(empty($reference)){
            throw new Common_Model_Exception('Reference is Null!');
        }
        $condition = 'reference=? AND expire > ?';
        $vars = array($reference,Common_Util_Date::getUnixTimestamp());
        
        return $this->countIf($condition,$vars) > 0;
    }
    
    /**
     * 清除过期的临时数据
     * 
     * @return string
     */
    protected function _clearExpiredData(){
        $condition = 'expire < ?';
        $vars = array(Common_Util_Date::getUnixTimestamp());
        $this->destroyAll($condition,$vars);
    }
}
/**vim:sw=4 et ts=4 **/
?>