<?php
/**
 * Model Common_Model_Point
 * 
 * generated by gen-model task.
 */
class Common_Model_Point extends Common_Model_Table_Point {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * 花费积分标识
     * 
     * @var int
     */
    const ACTION_PAYOUT = -1;
    /**
     * 赚取积分标识
     * 
     * @var int
     */
    const ACTION_INCOME = 1;
    /**
     * @return Common_Model_Point
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function beforeValidation(){
        if($this->isNew()){
            $this->setCreatedOn(date('Y-m-d H:i:s'));
        }
        return true;
    }
    
    public function validate(){
        if($this->isNew()){
            $fields = array('user_id','value','balance');   
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            return False;
        }
        return true;
    }
    /**
     * 记录积分明细
     * 
     * @param int $user_id
     * @param int $type
     * @param float $value
     * @param float $balance
     * @param string $description
     * @return mixed
     */
    public function writePointLog($user_id,$type,$value,$balance,$description){
    	//insert into database
    	$this->setIsNew(true);
    	$this->setId(null);
    	
    	$this->setUserId($user_id);
    	$this->setType($type);
    	$this->setValue($value);
    	$this->setBalance($balance);
    	$this->setDescription($description);
    	
    	$this->save();
    }
    
}
/**vim:sw=4 et ts=4 **/
?>