<?php
/**
 * Model Common_Model_Postoffice
 * 
 * generated by gen-model task.
 */
class Common_Model_Postoffice extends Common_Model_Table_Postoffice {
    
    //关系映射表
    protected $_relation_map = array(
    );
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    
    const DEFAULT_STATE = 1;
    /**
     * 发送失败标识
     * 
     * @var int
     */
    const FAIL_STATE = -1;
    /**
     * 发送成功标识
     *
     * @var int
     */
    const SENDER_SUCCESS_STATE = 2;
    /**
     * 锁定状态
     * 
     * @var int
     */
    const LOCK_STATE = 0;
    /**
     * @return Common_Model_Postoffice
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
    public function beforeValidation(){
        if($this->isNew()){
        	$state = $this->getState();
        	if(is_null($state)){
        		$this->setState(self::DEFAULT_STATE);
        	}
        }
        return true;
    }
    
    public function validate(){
        if($this->isNew()){
            $fields = array('mailto','subject','body');   
        }else{
            $fields = array('id');
        }
        if(!$this->validateRequird($fields)){
            return False;
        }
        return true;
    }
    
    /**
     * 从外部接收一封信
     * 
     * @return bool
     */
    public function receive($mailto,$subject,$body,$mailfrom=null,$from_name=null){
    	if(is_null($mailfrom)){
    		$mailfrom = 'ideepred@gmail.com';
    	}
    	if(is_null($from_name)){
    		$from_name = '深红邮件系统';
    	}
    	
    	$this->setId(null);
    	$this->setIsNew(true);
    	
    	$this->setMailto($mailto);
    	$this->setMailfrom($mailfrom);
    	$this->setFromName($from_name);
    	$this->setSubject($subject);
    	$this->setBody($body);
    	try{
    		$this->save();
    	}catch (Anole_ActiveRecord_Exception $e){
    		throw $e;
    	}
    	return true;
    }
}
/**vim:sw=4 et ts=4 **/
?>