<?php
/**
 * Model Common_Model_Sort
 * 
 * generated by gen-model task.
 */
class Common_Model_Sort extends Common_Model_Table_Sort {
    
    //关系映射表
    protected $_relation_map = array(
        'articles'=>array(
            'type'=>self::HAS_AND_BELONGS_TO_MANY,
            'class'=>'Common_Model_Article',
            'this_foreign_key'=>'sort_id',
            'other_foreign_key'=>'article_id',
            'join_table'=>'article_sort'
        )
    );
    const OPEN_STATE = 1;
    
    const CLOSE_STATE = 0;
    /**
     * 默认的magic field
     */
    protected $_magic_field = array();
    /**
     * @return Common_Model_Sort
     */
    public static function getModel($data=array(),$class=__CLASS__){
        return parent::getModel($data,$class);
    }
    
}
/**vim:sw=4 et ts=4 **/
?>